print("===============================================================")
print("Soal 1 Tugas 7")
print("===============================================================")

def fungsistring(kata) :
    print("\nKondisi awal : ", kata)
    print("\n(",kata,") Kata awal setelah diberi fungsi capitalize")
    a = kata.capitalize()
    print(a)
    print("\n(",kata,") Kata awal setelah diberi fungsi endswith menjadi")
    print(kata.endswith('World'))
    print("\n(",kata,") Kata awal setelah diberi fungsi upper dan lower menjadi")
    x = kata.upper()
    y = kata.lower()
    print(x)
    print(y)
print("Gunakan koma untuk pemisah")
katakata = input('Ketik kata-kata yang anda inginkan:')
fungsistring(katakata)